name: Execute tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  acao_inicial:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run TS validator
        run: yarn tsc

      - name: Run Tests
        run: yarn test:all
